tests/test_threading.py
whatshap/cli/polyphase.py
whatshap/threading.py
whatshap/vcf.py

I added a new parameter for whatshap polyphase, with which the phasing set information can be included into the VCF on a haplotype level. In order to do this, a new custom format field "HS" was added the VCF writer and a list of values (one for each phase) is added. This feature was promised in a recent submission about the polyploid phaser of whatshap, so it needs to be added at some point.
Disclaimer 1: I am always a bit insecure when editing the vcf.py, so someone should review whether I violated any conventions.
Disclaimer 2: A lot of files were reformatted after running black. I needed to do this, because otherwise the test builds with black would fail. I remember that the unit tests were not supposed to be reformatted, but since tox internally runs "black --check whatshap/ tests/ …

Haploid phasing blocks

---

whatshap/cli/stats.py

This implementation is similar to how it was done in e.g. `whatshap phase`. While this does not fix the requested comma-separate input of chromosomes in #207, it achieves the same thing.

Allow multiple `--chromosome` arguments in `whatshap stats` (#207)

---

tests/test_run_haplotag.py
whatshap/cli/haplotag.py

For backwards compatibility, we need to allow `chr:start:end` in addition to `chr:start-end` when specifying a `--region` for `whatshap haplotag`.
I have also simplified the tests a bit. It’s not necessary to run the full `run_haplotag` function just to see whether an invalid region is correctly caught, we should instead test the parsing code directly.
See #262

Allow colon in region specifications

---

tests/test_run_haplotag.py
tests/test_utils.py
whatshap/cli/haplotag.py
whatshap/utils.py

- moves Region dataclass from haplotag to utils
- moves Region dataclass specific test to utils test module
- prepare using more fine-grained region definitions in other cli modules besides haplotag (e.g. suggested for #270)

Move Region dataclass

---

src/polyphase/readscoring.cpp
tests/test_run_polyphase.py
whatshap/cli/__init__.py
whatshap/cli/polyphase.py
whatshap/core.pyx
whatshap/polyphaseplots.py

This pull request contains a parallelization for the polyphase module. The algorithms themselves are not changed, but the phasing is parallelized on a block-level. This means that it can only achieve a speed-up, if there are actually some weekly (or un-)connected components in the readset. The implementation uses the `multiprocessing` library of Python, which forks the main process. A thread-level parallelization is technically not possible with Python due the Global Interpreter Lock.
The parallelization must be requested via the `--threads` parameter when executing the module. The default is 1 thread, which invokes no fork at all. Running multiple threads increases the memory consumption (see example below), because the worker threads create local data structures, which are needed for …

Parallel polyphase

---

CHANGES.rst
tests/test_run_phase.py
whatshap/cli/phase.py

This removes `--full-genotyping` from `whatshap phase`.
What about `--distrust-genotypes`, should that also be removed? Then I’ll add that to this PR.
Closes #248

Remove --full-genotyping option

---

src/polyphase/trianglesparsematrix.h

Recent g++ requires this include (it is not included by the other anymore)

Add missing C++ header

---

tests/data/phased_single_sample1.vcf
tests/data/phased_single_sample2.vcf
tests/test_run_compare.py
whatshap/cli/compare.py

Fix #334.
To make this work I had to change sample name handling to use a list contain the sample name for each input file.

Add option --ignore-sample-name to compare.py 

---

CHANGES.rst
whatshap/merge.py

This undoes a copy&paste error by de-denting the last for loop in the `ReadMerger.merge`.
This is done in commit except 2c8b242, all the others are refactoring.
The first commit that added the merge functionality (copied over from hapCHAT) is 6cbbee3, and that one shows that indentation was different than what we have now. (It also makes a lot more sense this way.)
I’m not sure it works the way it is supposed to, yet, but at least it doesn’t crash anymore and doesn’t take an eternity to finish. It’s now quite quick actually (increases runtime by sth. like 10-20%)
Closes #208

Fix --merge-reads option

---

.github/workflows/ci.yml
pyproject.toml
setup.py
tox.ini

I had to yank the WhatsHap 1.2 release because I switched to `build-backend = "setuptools.build_meta"` in `pyproject.toml`, which for some reason caused neither `pyproject.toml` nor `setup.py` to be included in the tarball (sdist).
When fixing this, I had problems with the custom `BuildExt` class, which we modified to run `cythonize()` on the `.pyx` files. I simplified the build system a bit by assuming that Cython is always installed. This now works reliably due to `pyproject.toml`. We can then always run `cythonize`, which also allows us to get rid of the custom `SDist` class.
All this is simpler and more in line with current best practices for Cython projects.
I also added an extra test that just creates an sdist and builds a wheel from that. If that test had been in place, we would …

Fix packaging issues by modernizing cythonizing of extensions

---

whatshap/cli/haplotag.py
whatshap/utils.py

`whatshap haplotag` is used in a number of pipelines including [clair3](https://github.com/HKU-BAL/Clair3)'s variant calling. In these pipelines it can be a bottleneck since a) its a fairly slow serial step b) it usually occurs in a synchronisation step so no other tasks can be accomplised until the tagging has finished.
A quick profiling reveals 25% of time is spent on the line:
```
for alignment in bam_reader.fetch(contig=chrom, start=start, stop=end):
```
and 50% of the time is spent on the line:
```
bam_writer.write(alignment)
```
with the rest of the time being spent on more productive matters.
This PR alleviates some of the bottleneck that `whatshap haplotag` can cause by exposing the threads option of the `pysam.AlignmentFile` class to allow use of an htslib threadpool for output …

Use threads option of pysam for haplotag output

---

CHANGES.rst
src/polyphase/edgeheap.cpp
src/polyphase/inducedcostheuristic.cpp
src/polyphase/inducedcostheuristic.h
src/polyphase/staticsparsegraph.cpp
src/polyphase/staticsparsegraph.h
src/polyphase/trianglesparsematrix.h
tests/test_clusterediting.py

I found a nice shortcut in the cluster editing heuristic, which does not change the results (or at least it should not and I did not find any differences so far), but makes the heuristic run in less than a third of the old time. This makes the regular polyphase algorithm 20-30% faster. The upcoming genetic polyphase should profit much more, because the cluster editing is much more of a bottleneck there, at least on large instances. I also added/updates the testcases for cluster editing.
I did not edit the `CHANGES.rst` yet, because I first wanted to wait for approval.

Cluster editing speedup

---

whatshap/cli/haplotag.py
whatshap/variants.py

This PR includes some speed improvement to the `haplotag` command. Some improvements only apply to linked reads, e.g. 6954d1fd3f2a714c9e7080783029da84c4869599. 
I benchmarked using a linked-read dataset of about 1M reads.
**Before**
```
Benchmark #1: whatshap haplotag chunks/chr22_14029500_18289499.calling.phased.vcf.gz chunks/chr22_14029500_18289499.calling.bam --linked-read-distance-cutoff 30_000 --reference ../chr22_testdata/chr22.fasta --ignore-read-groups > /dev/null
Time (mean ± σ):     12.036 s ±  0.156 s    [User: 11.856 s, System: 0.162 s]
Range (min … max):   11.810 s … 12.296 s    10 runs
```
**After**
```
Benchmark #1: whatshap haplotag chunks/chr22_14029500_18289499.calling.phased.vcf.gz chunks/chr22_14029500_18289499.calling.bam --linked-read-distance-cutoff 30_000 …
```

whatshap haplotag - Speed improvments

---

whatshap/cli/stats.py
whatshap/vcf.py

I noticed that when using `whatshap stats` with `--chromosomes` the entire VCF is still read, which is very slow. This PR does two things. 
- If the VCF is indexed (.tbi or .csi) --> lookup chromosomes of interest (given by `--chromosomes`) directly
- If the VCF is not indexed --> stop reading if all chromosomes of intest have been seen

whatshap stats - Speed up chromosome lookup 

---

tests/data/phased_overlapping.vcf
tests/test_run_stats.py
whatshap/cli/stats.py

Split interleaved phase blocks to maintain as much of the phased variants as possible. This will make NG50 values a bit more fair compared to how they were calculated previously. 
If one phase block is fully encompassed by another block the inner block would determine the end of the outer block on the left side. The right side variants in the outer block were however scrapped in the current version leading to some deflation of the NG50 value. 
I made a small example below to clarify.
**Original phase blocks**
```
Phase block 1:    A--G--G--T----C------C--T--C
Phase block 2:               A----G--C
```
**Previous split**
```
Phase block 1:   A--G--G--T
Phase block 2:              A--G--C
```
**Updated split**
```
Phase block 1.1:  A--G--G--T
Phase block 1.2:                       C--T--C …
```

whatshap stats - Update NG50 calculation

---

whatshap/cli/stats.py

Small change in the case we have large stats valyes. Before these would be shifted if the are longer than 8 digits. Now every value is shifted along to keep thing looking nice. Look at `Sum of lengths` in the example below.
**Before**
```
---------------- Chromosome chr1 ----------------
Variants in VCF:   354236
Heterozygous:   208485 (  176461 SNVs)
Phased:   204892 (  175025 SNVs)
Unphased:     3564 (not considered below)
Singletons:       29 (not considered below)
Blocks:      151
Block sizes (no. of variants)
Median block size:      247.00 variants
Average block size:     1356.90 variants
Largest block:    13975    variants
Smallest block:        2    variants
Block lengths (basepairs)
Sum of lengths: 219115273    bp
Median block length:   130575.00 bp
Average block length: …
```

whatshap stats - format printout

---

CHANGES.rst
doc/guide.rst
tests/test_run_stats.py
whatshap/cli/stats.py

fix #400 
Fixes inflated stats for block lengths in `whatshap stats` if there are overlapping blocks, also see  https://github.com/whatshap/whatshap/pull/384. 
I tested on chromosome `SUPER_3` (116801625 bp) in the VCF referenced in issue #400 where there were a lot of overlapping blocks. 
**Before** 
```
Sum of lengths: 1036875048    bp
Median block length:        493.00 bp
Average block length:      16018.71 bp
Longest block:   75095876    bp
Shortest block:          1    bp
Block NG50:          0    bp
```
**After**
```
Sum of lengths: 48207739    bp
Median block length:      492.00 bp
Average block length:      744.53 bp
Longest block:    15389    bp
Shortest block:        1    bp
Block NG50:        0    bp
```
As you can see there is a drastic reduction in `Sum of lengths`, `Average …

whatshap stats - Calculate all length statistics on split blocks

---

tests/test_reorder.py
whatshap/polyphase/reorder.py

In #449 a very running time for polyphase's reording stage was reported when using ploidies above 4. The cause is the an ILP which is used to find the optimal permutation of phases within confident blocks (the haplotype segments are clear, but not how they need to be linked between these blocks). For now, the ILP is bypassed, because an optimal solution can be conducted quite easily, if no pre-phasing information is used. The latter is still a very experimetnal feature and will require additional work anyways. For "normal" users the issue should be fixed, though.

Workaround for issue 449

---

src/genotype.h
src/polyphase/allelematrix.h
src/polyphase/haplothreader.h
src/polyphase/inducedcostheuristic.h
src/polyphase/readscoring.h
src/polyphase/staticsparsegraph.h
src/polyphase/switchflipcalculator.h
src/polyphase/trianglesparsematrix.h
src/polyphase/tuple.h
src/polyphase/tupleconverter.h

The libstdc++ packaged with GCC 13.2.0 (and possibly earlier versions) requires <cstdint> to be explicitly included in places where it may have been implicitly included before.

Add #include <cstdint> where needed

---

CHANGES.rst
tests/test_read_grouping.py
whatshap/cli/phase.py
whatshap/variants.py

Adding support for supplementary alignments from issue https://github.com/whatshap/whatshap/issues/516 with flag --use-supplementary.
The supplementary alignment must have the same orientation as the primary and be within a distance of at most 100,000 from the primary alignment. This distance parameter can be adjusted using the --supplementary-distance option. The alignments may intersect. To form the new read from the alignments, the algorithm selects only positions where alignments fully agree with the allele of the variant and uses this allele.

support of supplementary alignments in phase

---

CONTRIBUTING.rst
doc/develop.rst

Prompted by PR #546. I copied this from [Cutadapt’s Contributing guide](https://cutadapt.readthedocs.io/en/stable/develop.html#contributing) and adjusted it a little bit.

Add contributing guidelines

---

doc/guide.rst
tests/data/pacbio/variants.vcf
tests/data/pacbio/variants_haplotagphase.vcf
tests/test_run_haplotagphase.py
whatshap/cli/__init__.py
whatshap/cli/haplotagphase.py
whatshap/variants.py

Sometimes we can have two non-reference alleles. Previously, there was no way to support them because the phase and haplotagphase commands didn't support multi-allelic variants. I need to ensure that I choose alleles only from the list provided by the GT tag. It requires small changes in the logic around allele detection.

Add support of multi-allelic variants into haplotagphase

---

CHANGES.rst
whatshap/variants.py

I found a performance hazard in the `realign` routine: For every read alignment and every variant, the list of cigar operations needs to be split at the variant positions. This is necessary to obtain the intervals on the read and reference sequences for the actual realignment (= edit distance calculation). In the current implementation, the split function always creates a full copy of the cigar list, even though only a very small fraction of it is actually used for each realignment. This has been resolved by computing two iterators for the left and right split that lazily read from the full list.
This improvement saves about 1/3 of the total BAM processing time. For testing I used on one of the `polyphase` instances from my thesis (80X simulated reads from chr1 of two human samples, …

Faster realignment

---

whatshap/cli/__init__.py
whatshap/utils.py

This avoids the confusing error message when opening a gzip-compressed FASTA reference, which mentions "e.g. a BAM file" and therefore incorrectly leads the user to think that something is wrong with the BAM inputs.
Closes #534

Nicer message when reference compressed with gzip instead of bgzip

---

tests/test_genotyping.py
tests/test_pedigreegenotyping.py
tests/test_run_learn.py
whatshap/testhelpers.py

This pull request focuses on stabilizing unit tests on macOS by adding robust likelihood comparisons, adjusting scaling factors to avoid numerical issues, and improving file comparison behavior.
Note: The run_learn function remains unstable, producing different results when run multiple times.

Fix tests on macOS

---

whatshap/vcf.py

This is to fix a failing test when using pysam 0.23 (see below), which now throws a `ValueError` when reading a VCF without header. @marcelm I wanted to give you a chance to see this before I merge it because I think you wrote [missing_headers](https://github.com/whatshap/whatshap/blob/87faeab6856431e8f7ff2c340d87943f7a2ac78a/whatshap/vcf.py#L881) and reported to pysam back then https://github.com/pysam-developers/pysam/issues/771.
```
______________________________________ test_vcf_with_missing_headers[whatshap] _______________________________________
algorithm = 'whatshap'
def test_vcf_with_missing_headers(algorithm):
with raises(CommandLineError):
>           run_whatshap(
phase_input_files=["tests/data/oneread.bam"],
variant_file="tests/data/missing-headers.vcf",
output="/dev/null", …
```

Catch ValueError thrown by pysam 0.23 when reading a VCF without header

---

whatshap/cli/genotype.py
whatshap/cli/phase.py

The help text shown for both `genotype` and `phase` listed the mother and father column in incorrect order. Fixes Issue #588.

Make help text on --ped more precise

---

whatshap/cli/phase.py

Implements a suggested improvement from Issue #557.

Improve log message when a trio is ignored because of selected samples

---

tests/data/pacbio/variants_haplotagphase_multisample.vcf
tests/test_run_haplotagphase.py
tests/test_run_phase.py
whatshap/cli/__init__.py
whatshap/cli/haplotagphase.py
whatshap/cli/phase.py
whatshap/utils.py
whatshap/vcf.py

The pull request introduces several changes to support working with multiple samples in the `haplotagphase` command.
- Updated the `run_haplotagphase` function to accept an optional sample parameter and handle cases where no sample is specified. If a sample is not provided, Whatshap does not modify the phasing information for the sample.

Support of multisample vcf for haplotagphase

---

pyproject.toml
setup.py

(where it should be). This gets rid of the optimization of not compiling the extension modules on Read the Docs. We need to solve this some other way (if at all).

Move list of dependencies into pyproject.toml

---

CHANGES.rst
pyproject.toml

setuptools changed how they interpret CFLAGS in 75.7.0 - they’re no longer appended to the existing CFLAGS, but replace them, which means the wheels are compiled without optimization.
Thanks @rhpvorderman!
See https://github.com/marcelm/cutadapt/issues/843

Fix slow wheels
