whatshap/whatshap

- src/polyphase/inducedcostheuristic.cpp
- whatshap/threading.py
Fixes #241 
Unfortunately, the resulting VCFs differ minimally to the previous state, but error-wise neither strictly better or worse.
> Solving issue 241

- CITATION.rst
- doc/guide.rst
Should fix issue 260. Provides some detailed information regarding the polyphase module.
> Added description for the polyphase module.

- whatshap/cli/phase.py
- whatshap/utils.py
- whatshap/vcf.py
> Log a warning only the first time for some types of problems

- src/polyphase/staticsparsegraph.cpp
So WhatsHap compiles on Alpine Linux.
> Change u_int64_t to the more standard uint64_t

- whatshap/cli/haplotag.py
> Remove duplicate lines introduced in 70da82

- whatshap/cli/stats.py
NG50 and N50 have a slightly different definition (NG50 needs an "assembly
size" as input, for N50 all input block/contig lengths are added up).
whatshap stats computes the NG50.
> stats: Write NG50 instead of N50

- whatshap/cli/split.py
> Re-enable gzipped list as input to whatshap split

- whatshap/cli/polyphase.py
- whatshap/polyphase/algorithm.py
- whatshap/polyphase/reorder.py
- whatshap/polyphase/threading.py
In case a new release version is coming up in order to make the polyploid version of haplotag available, I would like this fix to be included as well. I don't know yet whether #407 is actually fixed, but two other bugs are definitely eliminated with relatively small changes. I might update this branch, either to add a few testcases for the previously existing bug or to elaborate further on the error mentioned in #407 if it is still unfixed.
> Fixing issue 407

- whatshap/cli/stats.py
- Reduce complexity by factoring out parts of `run_stats`. 
- Improve legibility and simplified multiple sections of the code. 
- Improved typing in some sections. 
- Added missing printout from DetailedStats `variant_per_block_sum` that was only included in TSV.
> whatshap stats - Refactoring 

- doc/guide.rst
> Update docs for whatshap stats to match code

- doc/develop.rst
- pyproject.toml
> Attempt to reduce problems when using a Conda environment for development

- CHANGES.rst
I’m opening this PR as a way to notify all who are subscribed to this repository that I’m preparing to release version 1.7 of WhatsHap.
> Release version 1.7

- doc/installation.rst
> Clarify that -c bioconda is not sufficient

- .readthedocs.yaml
- doc/conf.py
- doc/requirements.txt
- tox.ini
This speeds up CI a little bit.
> Allow skipping install when building documentation

- CHANGES.rst
- tests/test_offspringscoring.py
- tests/test_polyphasegenetic.py
- tests/test_readsetreader.py
- tests/test_run_genotype.py
- tests/test_run_phase.py
- tests/test_run_polyphase.py
- tests/test_variantselection.py
- tests/test_vcf.py
- whatshap/cli/__init__.py
- whatshap/cli/compare.py
- whatshap/cli/genotype.py
- whatshap/cli/haplotag.py
- whatshap/cli/phase.py
- whatshap/cli/polyphase.py
- whatshap/cli/polyphasegenetic.py
- whatshap/cli/stats.py
- whatshap/polyphase/plots.py
- whatshap/vcf.py
> Enable --indels by default

- .readthedocs.yaml
See https://blog.readthedocs.com/use-build-os-config/
> Add build.os key to RTD configuration

- whatshap/polyphase/algorithm.py
- whatshap/polyphase/reorder.py
Small fix(es) for some corner cases in the polyphase module (see #480 ).
Since the changes are very small, I will merge this in 24h if there are no objections.
> Fixing corner cases discovered in #480

- CHANGES.rst
- whatshap/cli/polyphase.py
A small fix I forgot to merge for #485 .
> Fixed key error, mentioned in issue #485.

- tests/test_run_polyphase.py
- whatshap/cli/polyphase.py
This is the fix from branch `issue-441`, but with an added unit test and rebased on top of main.
Closes #496
See #441
> Fix polyphase segfault

- tests/test_run_haplotag.py
- whatshap/cli/haplotag.py
> Allow running haplotag multiple times on the same file 

- tests/test_run_polyphase.py
- whatshap/polyphase/algorithm.py
Fixes the bug described in #549 .
> Fixed block cut sensitivity 0-preset

- .github/workflows/ci.yml
- CHANGES.rst
- pyproject.toml
- tox.ini
Also needed to bump Cython to version 3.
> Support Python 3.13

- whatshap/cli/polyphasegenetic.py
> Polyphasegenetic compatibility indels

- CHANGES.rst
- tests/test_run_phase.py
- whatshap/cli/genotype.py
- whatshap/cli/haplotagphase.py
- whatshap/cli/phase.py
- whatshap/cli/polyphase.py
- whatshap/cli/polyphasegenetic.py
- whatshap/utils.py
Added option for excluding chromosomes. See https://github.com/whatshap/whatshap/issues/554 for the motivation.
> Flag to exclude chromosomes

- .gitignore
- CHANGES.rst
- pyproject.toml
- tests/test_variants.py
- tox.ini
- whatshap/variants.py
> Fix bug in distance function (Issue #587) and add corresponding tests

- whatshap/vcf.py
Implemented the refactorings suggested in https://github.com/whatshap/whatshap/pull/591.
> refactored missing_headers function

- tests/test_reorder.py
- whatshap/cli/polyphase.py
- whatshap/polyphase/__init__.py
- whatshap/polyphase/algorithm.py
- whatshap/polyphase/reorder.py
- whatshap/polyphase/solver.pyi
- whatshap/polyphase/threading.py
I created this branch some time last year because I was unsatisfied with the Python code quality of the polyphase module. The branch became stale at some point due to a lack of time but now I managed to verify that it is in a working condition. There is certainly more one could improve but it is better than before and I did not find any regressions in my tests. In order to tackle other polyphase-related issues, I would like to merge this state back. The changes are not intended to do any optimization or bring new features - it is just refactoring and type annotations. Therefore, I did not update the changelog.
Feel free to comment, otherwise I will merge it in the next couple of days. Anything outside the polyphse module should not be affected by the changes.
> Polyphase code quality
